<a href="https://colab.research.google.com/github/Shayankr/AI_and_ComputerVision/blob/master/PyTorch_00_Fundamnetals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Fundamental...
### Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
print(f"Hello, I am going to learn PyTorch!")

Hello, I am going to learn PyTorch!


In [2]:
! nvidia-smi

Sun Oct 16 18:45:25 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
# Import Necessary Libraries

import torch
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to tensors

#### Tensor is the building block. Creating tensor

PyTorchc tensors are created using "torch.tensor()" = https://pytorch.org/docs/stable/tensors.html


In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim # Scalar has no dimensions--its a single value

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
np.array(vector).shape

(2,)

In [11]:
vector

tensor([7, 7])

In [12]:
type(vector)

torch.Tensor

In [13]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
MATRIX[0]

tensor([7, 8])

In [17]:
MATRIX[1]

tensor([ 9, 10])

In [18]:
MATRIX[0][1]

tensor(8)

In [19]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

In [20]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

https://pytorch.org/docs/stable/generated/torch.rand.html

In [24]:
# Create a random number of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2903, 0.6641, 0.7233, 0.9958],
        [0.1967, 0.4819, 0.8261, 0.1318],
        [0.6119, 0.2076, 0.2097, 0.9717]])

In [25]:
random_tensor.ndim

2

In [26]:
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[0.9651, 0.2695, 0.5835, 0.5518, 0.9296, 0.9135, 0.5226, 0.6477,
          0.7863, 0.9424],
         [0.5248, 0.6574, 0.8880, 0.9458, 0.5170, 0.0348, 0.8209, 0.4784,
          0.0577, 0.7403],
         [0.8817, 0.4438, 0.0557, 0.1398, 0.4988, 0.8373, 0.5299, 0.5849,
          0.8194, 0.3638],
         [0.3720, 0.8278, 0.2393, 0.0834, 0.1558, 0.4524, 0.5346, 0.5438,
          0.1731, 0.7272],
         [0.6624, 0.5915, 0.9880, 0.1801, 0.3167, 0.8882, 0.0284, 0.7605,
          0.6708, 0.5851],
         [0.7501, 0.8765, 0.7647, 0.7631, 0.2253, 0.1695, 0.3070, 0.0855,
          0.4540, 0.3725],
         [0.1085, 0.9789, 0.9053, 0.4673, 0.8894, 0.9774, 0.4481, 0.3040,
          0.1235, 0.3748],
         [0.1861, 0.8072, 0.2088, 0.6554, 0.3299, 0.8242, 0.8679, 0.8751,
          0.5605, 0.3005],
         [0.8571, 0.0909, 0.9290, 0.1867, 0.2809, 0.4939, 0.5462, 0.6215,
          0.8931, 0.1518],
         [0.8961, 0.4089, 0.8743, 0.2473, 0.9685, 0.5947, 0.9397, 0.7042,
          0.6312,

In [27]:
random_tensor = torch.rand(2,10,10)
random_tensor

tensor([[[0.4774, 0.1952, 0.3053, 0.4518, 0.4184, 0.1587, 0.9225, 0.0182,
          0.8506, 0.2428],
         [0.6693, 0.5402, 0.8078, 0.0574, 0.0824, 0.9900, 0.2606, 0.6261,
          0.1246, 0.2526],
         [0.4445, 0.3495, 0.8951, 0.3224, 0.7985, 0.0823, 0.5174, 0.9101,
          0.7387, 0.0939],
         [0.5845, 0.5616, 0.3267, 0.8493, 0.6218, 0.2748, 0.8808, 0.9084,
          0.9099, 0.9809],
         [0.1603, 0.4444, 0.9826, 0.9599, 0.9708, 0.2493, 0.9137, 0.7977,
          0.9075, 0.8829],
         [0.3190, 0.6906, 0.3158, 0.0203, 0.6667, 0.9576, 0.2335, 0.8306,
          0.8172, 0.2614],
         [0.9267, 0.2538, 0.5453, 0.9710, 0.8685, 0.0860, 0.4414, 0.2048,
          0.2366, 0.2553],
         [0.1456, 0.3750, 0.2979, 0.4085, 0.3807, 0.9731, 0.6146, 0.5497,
          0.5437, 0.8812],
         [0.7182, 0.6236, 0.8326, 0.4421, 0.2994, 0.2757, 0.5744, 0.2756,
          0.0999, 0.9862],
         [0.6561, 0.2901, 0.8513, 0.3490, 0.2868, 0.1259, 0.4088, 0.6801,
          0.7470,

In [28]:
random_tensor.ndim

3

In [29]:
random_tensor.size()

torch.Size([2, 10, 10])

In [30]:
random_tensor.shape

torch.Size([2, 10, 10])

In [31]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224,))  # height, width,colour channel (R,G,B)

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [32]:
list_ =[1,2,3,4]
for i,j in enumerate(list_):
  print(f"index is: {i} and value at this is {j}")

index is: 0 and value at this is 1
index is: 1 and value at this is 2
index is: 2 and value at this is 3
index is: 3 and value at this is 4


In [33]:
torch.rand(5)

tensor([0.1023, 0.7113, 0.8608, 0.1910, 0.2533])

### Zeros and Ones

In [34]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
random_tensor = torch.rand(3,4)

In [36]:
zeros*random_tensor  # Element wise

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Create a tensor of all ones

ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

In [39]:
random_tensor.dtype

torch.float32

### Creating a range of tensors

In [40]:
# Use torch.range()
torch.range(0,10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
torch.arange(1,10).dtype

torch.int64

In [43]:
torch.arange(1,10.5)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
torch.arange(1,10.5).dtype

torch.float32

In [45]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [46]:
range_ = torch.arange(start=0, end=1000, step=77)
range_

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [47]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# Creating tnsors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is  one of the 3 big errors you'll run into PyTorch & Deep learning:

1. Tensors not right datattype
2. Tensors not right shape
3. Tensors not on the right device

In [49]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32) # it's by default dtype=None
float_32_tensor

tensor([3., 6., 9.])

In [50]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # What datatype is the tensor
                               device=None, # device ="cude" -- fro GPU --means-- What device is your tensor on
                               requires_grad=False)  # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [51]:
# now,
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [52]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
# torch.float -- float32
# torch.half -- float16

In [54]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [55]:
(float_16_tensor * float_32_tensor).dtype  # data-TypeCasting

torch.float32

In [56]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [57]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [58]:
(float_32_tensor*int_32_tensor).dtype  # dataTypecasting

torch.float32

In [59]:
int_64_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_64_tensor

tensor([3, 6, 9])

In [60]:
int_64_tensor.dtype

torch.int64

### Getting information from Tensors

1. tensors not right datatype -- to do get datattype from a tensor, can use `tensor.dtype`
2. Tensors not right shape -- to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device -- to egt device from a tensor, can use `tensor.device`


In [61]:
# create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9438, 0.2106, 0.3935, 0.8878],
        [0.6083, 0.0921, 0.0893, 0.3871],
        [0.3596, 0.2839, 0.7319, 0.0731]])

In [62]:
# Find out details about some tensor
print(some_tensor)
# print()
print(f"Datatype of tensors: {some_tensor.dtype}")
# print()
print(f"Shape of Tensor: {some_tensor.size()}")
# print()
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9438, 0.2106, 0.3935, 0.8878],
        [0.6083, 0.0921, 0.0893, 0.3871],
        [0.3596, 0.2839, 0.7319, 0.0731]])
Datatype of tensors: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operatins)

 Tensor operations include:
 * Addition
 * Subtraction
 * Multiplication
 * Division
 * Matrix Multiplication


In [63]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [64]:
# multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [65]:
# Subtract 10
tensor-10

tensor([-9, -8, -7])

In [66]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [67]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing Multiplication in neural networks and deep learning:

1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

There are two main rules taht performing matrix multiplication needsd to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work.
* `(2,3) @ (3,2)` will work.
* `(3,2) @ (2,3)` will work.

In [68]:
# Element wise multiplication
print(tensor,"*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [69]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [70]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [71]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 528 µs, sys: 0 ns, total: 528 µs
Wall time: 742 µs


In [72]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 32 µs, sys: 6 µs, total: 38 µs
Wall time: 40.5 µs


tensor(14)

In [73]:
import time

In [74]:
start_time=time.time()
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)
end_time=time.time()
print(f"Time taken is: {(end_time-start_time)*1000} msec")

tensor(14)
Time taken is: 0.5619525909423828 msec


In [75]:
# Matrix - multiplictaion

tensor @ tensor

tensor(14)

In [76]:
%%time
tensor @ tensor

CPU times: user 28 µs, sys: 5 µs, total: 33 µs
Wall time: 36.5 µs


tensor(14)

In [77]:
# multiply

torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[1.6405, 2.4607, 2.5735],
        [2.7468, 2.4660, 2.9887],
        [2.6566, 3.4603, 3.7117]])

In [78]:
torch.matmul(torch.rand(10,3), torch.rand(3,10))

tensor([[0.8894, 0.6955, 0.8683, 0.5871, 0.8691, 1.4155, 1.2356, 0.8449, 1.3875,
         1.5549],
        [1.1587, 0.7790, 0.6959, 0.4294, 0.3544, 0.7531, 1.4796, 0.5528, 0.9280,
         0.6055],
        [0.9722, 0.6243, 0.6655, 0.4289, 0.5373, 0.9518, 1.2742, 0.6407, 1.1104,
         0.8066],
        [0.7675, 0.4008, 0.6480, 0.4467, 0.8696, 1.3360, 1.0625, 0.8382, 1.5255,
         1.1140],
        [0.7318, 0.3810, 0.4944, 0.3271, 0.5469, 0.8889, 0.9708, 0.5953, 1.0957,
         0.6385],
        [0.5690, 0.3742, 0.3494, 0.2179, 0.2066, 0.4121, 0.7305, 0.2960, 0.5046,
         0.3288],
        [0.4021, 0.3568, 0.3367, 0.2161, 0.1892, 0.3726, 0.5327, 0.2299, 0.3303,
         0.4852],
        [0.7798, 0.5077, 0.7362, 0.5055, 0.8848, 1.3836, 1.0907, 0.8412, 1.4631,
         1.3385],
        [0.7818, 0.6029, 0.6425, 0.4201, 0.5007, 0.8834, 1.0457, 0.5533, 0.8914,
         0.9566],
        [0.2890, 0.2207, 0.3382, 0.2362, 0.4208, 0.6472, 0.4216, 0.3752, 0.6319,
         0.7010]])

In [79]:
torch.matmul(torch.rand(10,3), torch.rand(3,10)).size()

torch.Size([10, 10])

In [80]:
torch.matmul(torch.rand(10,3), torch.rand(3,10)).shape

torch.Size([10, 10])

### One of the most common errors in Deep Learning: shape-errors

In [81]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as tensor.matmul(It's an alies)
#torch.matmul(tensor_A, tensor_B)

#Check Shape

In [82]:
#tensor_A.shape, tensor_B.shape

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

In [83]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [84]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [85]:
# Transposed matrix-multiplictaion
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [86]:
output = tensor_A @ tensor_B.T
print(f"Output is: \n{output}")
print(f"Output matrix shape is: {output.shape}")

Output is: 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output matrix shape is: torch.Size([3, 3])


## Finding the min, max, mean, sum etc (tensor aggregation)

In [87]:
# Create a tensor
x = torch.arange(0,100,10)

In [88]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [89]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [90]:
# Find the mean
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [91]:
# Find the mean  -- NOTE: torch.mean() function requires a tensorof float32 dataType to work.
torch.mean(x,  dtype=torch.float32)

tensor(45.)

In [92]:
torch.mean(x.type(torch.float))

tensor(45.)

In [93]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [94]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [95]:
x.min()

tensor(0)

In [96]:
x.argmin()

tensor(0)

In [97]:
print(f"Max value is: {x.max()}, and it's index number is {x.argmax()}")

Max value is: 90, and it's index number is 9


In [98]:
x[9]

tensor(90)

In [99]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original one

* Stack -- Conactenates a sequence of tensors along a new dimension.
Combine multiple tensors on top of each other (vstack) or side by side (hstack)

* torch.vstack --
* torch.hstack --

* Squeeze -- removes all `1` dimensions from a tensor

* Unsqueeze -- add a `1` dimension to a target tensor

* Permute -- Return a view of the input with dimensions permuted (swapped) in a certain way

In [100]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [101]:
x_reshaped = x.reshape( (1,9))
x_reshaped, x_reshaped.size()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [102]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.size()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [103]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.size()

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [104]:
x_reshaped = x.reshape(1,-1)
x_reshaped, x_reshaped.size()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [105]:
x_reshaped = x.reshape(-1,3)
x_reshaped, x_reshaped.size()

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [106]:
x_reshaped = x.reshape(-1,9)
x_reshaped, x_reshaped.size()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [107]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [108]:
# Changing z changes x (Because a view of a tensor shares the same memory as the orihginal)

z[:,0] = 5
print(f"z is: {z} and \nx is: {x}" )  # Both will change

z is: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) and 
x is: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [109]:
# Stack tensors on top of each-other.

In [110]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [111]:
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [112]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [113]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [114]:
x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [115]:
x_stacked = torch.hstack([x,x,x,x])
x_stacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [116]:
torch.concat([x,x])

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [117]:
torch.concat([x,x,x],axis=0)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [118]:
torch.cat([x,x],axis=0)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [119]:
# torch.squeeze

In [120]:
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [121]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [122]:
torch.randn(2,3)

tensor([[ 0.6315, -0.3609,  0.8687],
        [ 0.2970, -0.9010, -1.1773]])

In [123]:
help(torch.squeeze)

Help on built-in function squeeze in module torch:

squeeze(...)
    squeeze(input, dim=None, *, out=None) -> Tensor
    
    Returns a tensor with all the dimensions of :attr:`input` of size `1` removed.
    
    For example, if `input` is of shape:
    :math:`(A \times 1 \times B \times C \times 1 \times D)` then the `out` tensor
    will be of shape: :math:`(A \times B \times C \times D)`.
    
    When :attr:`dim` is given, a squeeze operation is done only in the given
    dimension. If `input` is of shape: :math:`(A \times 1 \times B)`,
    ``squeeze(input, 0)`` leaves the tensor unchanged, but ``squeeze(input, 1)``
    will squeeze the tensor to the shape :math:`(A \times B)`.
    
    .. note:: The returned tensor shares the storage with the input tensor,
              so changing the contents of one will change the contents of the other.
    
    .. warning:: If the tensor has a batch dimension of size 1, then `squeeze(input)`
              will also remove the batch dimension,

In [124]:
y = torch.squeeze(x)

In [125]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [126]:
torch.squeeze(torch.tensor([[1],[2],[3],[4]]))

tensor([1, 2, 3, 4])

In [127]:
y.size()

torch.Size([2, 2, 2])

In [128]:
m = torch.randn(2,3,4,5,6,1)

In [129]:
m.size()

torch.Size([2, 3, 4, 5, 6, 1])

In [130]:
p=torch.squeeze(y)

In [131]:
p.size()

torch.Size([2, 2, 2])

In [132]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [133]:
x_reshaped.shape

torch.Size([1, 9])

In [134]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [135]:
x_reshaped.squeeze().shape

torch.Size([9])

In [136]:
# torch.unsqueeze() -- adds a single dimension to a target tensor at a specific dim(dimension)

print(f"Prevoius target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimanesion with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Prevoius target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [137]:
# torch.unsqueeze() -- adds a single dimension to a target tensor at a specific dim(dimension)

print(f"Prevoius target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimanesion with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Prevoius target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [138]:
# torch.unsqueeze() -- adds a single dimension to a target tensor at a specific dim(dimension)

print(f"Prevoius target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimanesion with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=-1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Prevoius target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [139]:
# torch.unsqueeze() -- adds a single dimension to a target tensor at a specific dim(dimension)

print(f"Prevoius target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimanesion with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=-2)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Prevoius target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [140]:
# torch.permute -- Rearrange the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3))  #[height,width,color_channel]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")  # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [141]:
x_original[1,1,:]

tensor([0.3253, 0.5244, 0.1872])

In [142]:
x_permuted[:,1,1]

tensor([0.3253, 0.5244, 0.1872])

In [143]:
x_original[0,0,0]

tensor(0.5156)

In [144]:
x_permuted[0,0,0]

tensor(0.5156)

##Indexing (Selecting Data from tensors)

Indexing is PyTorch is similar to indexing with NumPy

In [145]:
# Create  a tensor
x = torch.arange(1,10).reshape(1,3,3)

In [146]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [147]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [148]:
#Let's index on the middle bracket (dim=1)
x[0,0]

tensor([1, 2, 3])

In [149]:
x[0][0]

tensor([1, 2, 3])

In [150]:
#Let's  index on the most inner bracket (last dimensions)
x[0][0][0]

tensor(1)

In [151]:
x[0,0,0]

tensor(1)

In [152]:
# Let's use ":"
x[:,:,1]

tensor([[2, 5, 8]])

In [153]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & Numpy

Numpy is a popular scientific numerical computing library.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> torch.tensor.numpy()

In [295]:
# NUmpy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)  #tensor--default datatype-- float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [297]:
torch.from_numpy(array).type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [298]:
# Tensor to NumPy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()  # Default datatype of numpy array--float32
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [299]:
np.array(tensor)

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [300]:
tensor +numpy_tensor

tensor([2., 2., 2., 2., 2., 2., 2.])

In [301]:
(tensor +numpy_tensor).dtype

torch.float32

In [302]:
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

# NEXT NOTEBOOK